// SPDX-License-Identifier: GPL-2.0

/*
 * Copyright (C) 2020 Google LLC.
 */
#include <linux/lsm_hooks.h>
#include <linux/bpf_lsm.h>

/* Some LSM hooks do not have 0 as their default return values. Override the
 * __weak definitons generated by default for these hooks
 */
noinline int bpf_lsm_inode_getsecurity(struct inode *inode, const char *name,
				       void **buffer, bool alloc)
{
	return -EOPNOTSUPP;
}

noinline int bpf_lsm_inode_setsecurity(struct inode *inode, const char *name,
				       const void *value, size_t size,
				       int flags)
{
	return -EOPNOTSUPP;
}

noinline int bpf_lsm_task_prctl(int option, unsigned long arg2,
				unsigned long arg3, unsigned long arg4,
				unsigned long arg5)
{
	return -ENOSYS;
}

noinline int bpf_lsm_xfrm_state_pol_flow_match(struct xfrm_state *x,
					       struct xfrm_policy *xp,
					       const struct flowi *fl)
{
	return 1;
}

static struct security_hook_list bpf_lsm_hooks[] __lsm_ro_after_init = {
	#define LSM_HOOK(RET, NAME, ...) LSM_HOOK_INIT(NAME, bpf_lsm_##NAME),
	#include <linux/lsm_hook_names.h>
	#undef LSM_HOOK
};

static int __init bpf_lsm_init(void)
{
	security_add_hooks(bpf_lsm_hooks, ARRAY_SIZE(bpf_lsm_hooks), "bpf");
	pr_info("LSM support for eBPF active\n");
	return 0;
}

DEFINE_LSM(bpf) = {
	.name = "bpf",
	.init = bpf_lsm_init,
};
